version: '3.9'
services:
  nova_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - '8080:8000'